### ISSUE TITLE
Need to be change to []string

### ISSUE THREAD

**Issue by alejandrojnm** [civo/civogo#1]
i think insted of `string` need to be `[]string`

https://github.com/civo/civogo/blob/57fae6917c372e1dbf8fa927c3d0cc5c770a5fc8/instance.go#L68

**Comment by andyjeffries** [comment]
I agree.

**Comment by alejandrojnm** [comment]
Ok, but you don't make the change 😄

**Comment by andyjeffries** [comment]
Fixed in ab4ebaa
