### ISSUE TITLE
Resize volume

### ISSUE THREAD

**Issue by alejandrojnm** [civo/civogo#10]
**I have a question:**
I create a new volume and attach to one instance, can resize the volume??
in the UI you can't so i think it is not possible in the api

**The second question:**
This question is for the terraform provider, if you changed the size in the configuration of terraform, i can detach the volume, them resize and after attach again to the same instance @andyjeffries ?

**Comment by andyjeffries** [comment]
You shouldn't be able to resize a volume attached to an instance.

You should be able to do the second part @alejandrojnm , but may need to spin/keep checking to ensure it's done (it's not an immediate thing).
