### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by alejandrojnm** [civo/civogo#15]
@andyjeffries is possible to add more documentation in the api of [kubernetes](https://www.civo.com/api/kubernetes) the result show `"configuration": {}` inside of **installed_applications**, but what is inside of **configuration**, in order to implement the struct for that, it is possible to know the content

**Comment by andyjeffries** [comment]
I've added documentation to the page, but can't deploy it yet.

><p>The response is a JSON object that describes the initial setup of the cluster, 
> future calls to get clusters may return more information (as underlying nodes 
> are created, applications are installed, etc). The only difference in the details 
> sent in is that instead of <code>applications</code>, you receive an 
> <code>installed_applications</code> object, which has the name of the 
> application, post_install content, etc. The <code>configuration</code> 
> object of each application is a simple key/value listing of the configuration applied 
> to the application, e.g. plan size, randomly generated passwords, etc.</p>

So the `configuration` object is just a key/value list of configuration applied - there are no set list of keys, this can be anything depending on the marketplace app author.
