### ISSUE TITLE
Error in update, notes

### ISSUE THREAD

**Issue by alejandrojnm** [civo/civogo#2]
When you try to update the obtines notes, an error is this:
`&{failed instance_duplicate An instance with this name already exists, please choose another }`
this is the code i'm using:

```
client, _ := civogo.NewClient(apiKey)
instance, _ := client.GetInstance("586f58df-be0c-4c4b-9640-3b73612d56ba")
instance.Notes = "test notes"

update, err := client.UpdateInstance(instance)
if err != nil {
	fmt.Println(err)
}

fmt.Println(update)
```
but if i change the hostanme too, then it works
```
client, _ := civogo.NewClient(apiKey)
instance, _ := client.GetInstance("586f58df-be0c-4c4b-9640-3b73612d56ba")
instance.Notes = "test notes"
instance.Hostname = "new_hostname"

update, err := client.UpdateInstance(instance)
if err != nil {
	fmt.Println(err)
}

fmt.Println(update)
```

**Comment by andyjeffries** [comment]
Do you get the same error if you use curl? Trying to work out if this is an API issue, or a civogo issue?

**Comment by alejandrojnm** [comment]
Let me try and i let you know

**Comment by andyjeffries** [comment]
This is actually weirdness in the API if you pass in a value that is already set to the same value, I've fixed it for this case.
