### ISSUE TITLE
Unable to see which regions support Object Stores until error is thrown 

### ISSUE THREAD

**Issue by alechp** [civo/civogo#203]
### Summary
While attempting to provision a cluster in `phx1` with [Kubefirst](https://github.com/konstructio/kubefirst), was unable to because Civo lacked support for the Object Store in that specific region. 

There are hacky options (eg. attempt to provision an Object Store in each Civo region, keep track of which regions don't currently have errors and then maintain a list. However, that's prone to breaks whenever Civo updates. Would be great to get first-class support for this so we can consistently check.

### Logs
```
{"level":"info","time":"2024-09-03T23:39:54Z","message":"Error: Unknown error response - status: 400 Bad Request, code: 400, reason: {\"code\":\"database_region_feature_not_supported\",\"reason\":\"This feature is not supported in this region\",\"details\":\"Feature object_store is not supported in region phx1\"}\n"}
{"level":"info","time":"2024-09-03T23:39:54Z","message":"credential name: k1-state-store-civo-phx1-cscloud-hiokmn not found, creating"}
{"level":"info","time":"2024-09-03T23:39:54Z","message":"Error: Unknown error response - status: 400 Bad Request, code: 400, reason: {\"code\":\"database_region_feature_not_supported\",\"reason\":\"This feature is not supported in this region\",\"details\":\"Feature object_store is not supported in region phx1\"}\n"}
{"level":"info","time":"2024-09-03T16:40:00-07:00","message":"unable to get cluster 500 Internal Server Error, continuing"}
```

### Action item
Update `civogo` to allow us to search which region supports Object Store. 

### Relevant files
- https://github.com/civo/civogo/blob/v0.3.75/objectstore.go
- https://github.com/civo/civogo/blob/v0.3.75/region.go
- https://www.civo.com/api/object-stores

**Comment by alessandroargentieri** [comment]
The `GET /v2/regions` endpoint returns what resource is enabled, what is not for any region. For example, for phx1:

**Comment by alessandroargentieri** [comment]
Closing the issue
