### ISSUE TITLE
Create a new method in the client

### ISSUE THREAD

**Issue by alejandrojnm** [civo/civogo#22]
It is posible create a new method in the [client.go](https://github.com/civo/civogo/blob/master/client.go), like `SendSimplePost`, is for the case of test the webhook, so far is the only case need use a simple post.

**Comment by andyjeffries** [comment]
What would the method do? And how would you want to use it? Do you need me to write this or are you just asking if it's OK to add it?

**Comment by andyjeffries** [comment]
I'll close this issue for now, until we can get some explanation of what for/why this is needed.
