### ISSUE TITLE
Add new option to the snapshot module

### ISSUE THREAD

**Issue by alejandrojnm** [civo/civogo#36]
is it possible that when a snapshot has a cron defined, then the return of the api will have a field that says the next execution, but is it defined because it would be null, like this:

```json
{
    "id": "0ca69adc-ff39-4fc1-8f08-d91434e86fac",
    "instance_id": "44aab548-61ca-11e5-860e-5cf9389be614",
    "hostname": "server1.prod.example.com",
    "template_id": "0b213794-d795-4483-8982-9f249c0262b9",
    "openstack_snapshot_id": null,
    "region": "lon1",
    "name": "my-instance-snapshot",
    "safe": 1,
    "size_gb": 0,
    "state": "in-progress",
    "cron_timing": "5 4 * * sun",
    "next_execution": "2020-04-19 04:05:00",
    "requested_at": null,
    "completed_at": null
  }
```
the new option will be this `"next_execution": "2020-04-19 04:05:00"` and if the cron is no't define them this value will be null.

**Comment by alejandrojnm** [comment]
I implement in the side of terraform using this: `github.com/gorhill/cronexpr`

**Comment by andyjeffries** [comment]
Awesome, good work.
