### ISSUE TITLE
Switch to using named errors everywhere

### ISSUE THREAD

**Issue by andyjeffries** [civo/civogo#40]
We use a bunch of randomly generated errors through the client at the moment, we need to switch to using constant defined errors where possible, to allow users of the client to better determine which errors to just retry or which can be ignored for their purposes.

https://dave.cheney.net/2016/04/07/constant-errors

This isn't urgent @alejandrojnm , but when you're next looking for something.

**Comment by alejandrojnm** [comment]
ok, thx @andyjeffries i'm checking the doc
