### ISSUE TITLE
Add new record type to the DNS

### ISSUE THREAD

**Issue by alejandrojnm** [civo/civogo#42]
We need add new type of records to the DNS control

Record type:
- AAAA
- SRV

**Comment by andyjeffries** [comment]
"Need"? Has a customer requested this?

We can add them, but it'll likely wait until the control panel redesign James is working on.

**Comment by andyjeffries** [comment]
When we implement AAAA we need to be aware of:

> There are various ways of compressing IPv6 records, by removing leading zeros, and using “::” (just once) to omit a variable number of empty fields.
> 
> TinyDNS likes an uncompressed format without colon separators, like “fe80000000000000080aba55a2dca1b6” rather than “fe80::80a:ba55:a2dc:a1b6”. If you install ipv6calc (with apt-get install ipv6calc), you can use it to do the translation like this: ipv6calc –printfulluncompressed fe80::80a:ba55:a2dc:a1b6|tr -d :, using “tr” to strip the colons.

**Comment by andyjeffries** [comment]
TinyDNS formats:

`6fqdn:ip:ttl:timestamp:lo`
an AAAA record and the corresponding PTR record.

`Sfqdn:ip:x:port:priority:weight:ttl:timestamp:lo`
An SRV record. ip can be left empty. x is the target host name. port is required, priority and weight default to zero, which is fine if you have only one target, or have no preference as to the order in which your targets are tried.

**Comment by alejandrojnm** [comment]
in the current UI we don't have AAAA, but have a SRV record, I would just like to advance a little, so when it is available I will not have to modify the lib
