### ISSUE TITLE
UnknownError is Raised when Using Invalid API Key

### ISSUE THREAD

**Issue by martynbristow** [civo/civogo#44]
When accidentally setting an invalid API Key I receive:

martyn@macbook-pro civo-cli % civo --config .civo-test.json instance ls           
                                            
`Error: Listing instances failed with  Unknow Error`

Can we safely instead use AuthenticationFailedError?

Any request where the API Key is NOT ok results in:
`{"result":"requires_authentication","status":401}` (no bearer, empty bearer, invalid barer)

**It is confusing to the user to issue an UnknownError**

Also the response object uses: result, but the GoAPI assumes its called `reason` as per https://www.civo.com/api
This will also break the logic.

**Comment by alejandrojnm** [comment]
i will check this now, thanks @martynbristow for let it know
