### ISSUE TITLE
Kubernetes Cluster "generated_name" not available

### ISSUE THREAD

**Issue by cablespaghetti** [civo/civogo#52]
Hi,

I'm trying to build autoscaling again and it would be nice to have the cluster's "generated_name" available via the Go module for easier conversion between the Civo API node name and the Kubernetes node name.

Thanks!

**Comment by alejandrojnm** [comment]
Hi, @cablespaghetti , I really don't understand what you mean by "generated_name", could you explain me better, to see if I can help you or guide you

**Comment by andyjeffries** [comment]
The Civo API has a new field in the JSON `generated_name`. I don't think that's in the civogo objects.

**Comment by alejandrojnm** [comment]
Ok i will check this

**Comment by alejandrojnm** [comment]
Close by (43e5e9a)
