### ISSUE TITLE
Region is not set, when retrieving instance

### ISSUE THREAD

**Issue by dirien** [civo/civogo#55]
Hi,

when i use fn like GetInstance, FindInstance , the Region propertiy is not set.

https://github.com/civo/civogo/blob/1d48adde1dd56e40bd2cf81d1ebdb2f82fc94b35/instance.go#L20

According to the API, it should be set:

https://www.civo.com/api/instances#retrieving-an-instance

Is ther something i do wrong?

**Comment by alejandrojnm** [comment]
Hi @dirien the API don't retuen that filed, we are working to improve our API
