### ISSUE TITLE
API return 500 when the casing of a field is wrong

### ISSUE THREAD

**Issue by rberrelleza** [civo/civogo#8]
When passing a field with capital case instead of lower case, the API returns a 500. I think it would be better if it returned a 400 error, with a message  indicating the field that was wrong or missing.

**Comment by andyjeffries** [comment]
This isn't something we can really handle generically in Rails, so it's a specific error where you saw it. Can you please remind me which endpoint it was in and I'll ensure it raises the right error code.

**Comment by rberrelleza** [comment]
It was in the `/v2/dns/records` api I believe.

**Comment by andyjeffries** [comment]
Thanks, changed that post request to a 400 in our API server. Let me know if it's definitely fixed for you now please @rberrelleza :-)
